#!/bin/bash

#   Copyright 2013 Zynga Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

. /etc/init.d/functions
PIDFILE=/var/run/backup_merge.pid
exec &> >(tee /dev/stderr | logger -t 'zbasebackup' --)

command=$1

if [ $UID -ne 0 ];
then
    echo "Please run as root"
    exit 1
fi

status(){
    if [ -e $PIDFILE ];
    then
        PID=$(cat $PIDFILE)
        kill -s 0 $PID 2> /dev/null && echo "Backup merge daemon is running with pid $PID" && exit 0
        echo "Backup merge daemon is not running"
    else
        echo "Backup merge daemon is not running"
    fi
}

start(){
    if [ -e $PIDFILE ];
    then
        PID=$(cat $PIDFILE)
        kill -s 0 $PID 2> /dev/null && echo "Backup merge daemon is running with pid $PID" && exit 0
    fi

        /usr/bin/python26 /opt/zbase/zbase-backup/backup_merged start >/dev/null 2>&1 &

    sleep 1
    status | grep 'is running' 2> /dev/null
    if [ $? -eq 0 ];
    then
        echo Started backup merge daemon && exit 0
    else
        echo Failed to start backup merge daemon && exit 1
    fi
}


stop(){

    echo "Stopping backup merge daemon"
    /usr/bin/python26 /opt/zbase/zbase-backup/backup_merged stop >/dev/null 2>&1

    if [ $? -eq 0 ];
    then
        echo "Stopped backup merge daemon successfully"
    else
        echo "Backup merge daemon is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
    stop
    ;;
    status)
    status;
    ;;
    restart)
    stop; start 0;
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
esac


