#!/bin/bash 

#   Copyright 2013 Zynga Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

. /etc/init.d/functions


command=$1
status(){
    /usr/bin/python26 /opt/membase/membase-backup/blobrestore_utils/blobrestored status
}

start(){

    /usr/bin/python26 /opt/membase/membase-backup/blobrestore_utils/blobrestored start > /dev/null 2>&1 &
    if [ $? -eq 0 ];
    then
        echo "Started blobrestore daemon successfully"
    else
        echo "Failed to start blobrestore daemon"
    fi
}


stop(){

    /usr/bin/python26 /opt/membase/membase-backup/blobrestore_utils/blobrestored stop
}

case "$1" in
    start)
        status;
        start
        ;;
    stop)
    stop
    ;;
    status)
    status; 
    ;;
    restart)
    stop; start;
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
esac


