#!/bin/bash 

. /etc/init.d/functions


command=$1

if [ "$command" = "start" ];
then
    /usr/bin/python26 /opt/membase/membase-backup/mbbackup-incr-daemon start
    if [ $? -eq 0 ];
    then
        echo Started backup daemon
    else
        echo Failed to start backup daemon
    fi

fi


if [ "$command" = "stop" ];
then
	/usr/bin/python26 /opt/membase/membase-backup/mbbackup-incr-daemon stop
  
fi


