#!/bin/bash 

. /etc/init.d/functions

PATH=$PATH:/opt/membase/membase-backup/

command=$1

if [ "$command" = "start" ];
then
    daemon "{ mbbackup-uploader start > /dev/null 2>&1 }"

fi


if [ "$command" = "stop" ];
then
   mbbackup-uploader start
fi

