#!/bin/bash 

. /etc/init.d/functions
PIDFILE=/var/run/mbbackup.pid


command=$1
status(){
    if [ -e $PIDFILE ]; 
    then
        PID=$(cat $PIDFILE) 
        kill -s 0 $PID 2> /dev/null && echo "Backup daemon is running with pid $PID" && exit 0
        echo "Backup daemon is not running" 
    else
        echo "Backup daemon is not running" 
    fi
}

start(){
    if [ -e $PIDFILE ];
    then
        PID=$(cat $PIDFILE) 
        kill -s 0 $PID 2> /dev/null && echo "Backup daemon is running with pid $PID" && exit 0
    fi

    if [ $1 -eq 1 ];
    then
        /usr/bin/python26 /opt/membase/membase-backup/membase-backupd start-with-fullbackup >/dev/null 2>&1 
    else
        /usr/bin/python26 /opt/membase/membase-backup/membase-backupd start >/dev/null 2>&1 
    fi

    sleep 1
    status | grep 'is running' 2> /dev/null
    if [ $? -eq 0 ];
    then
        echo Started backup daemon && exit 0
    else
        echo Failed to start backup daemon && exit 1
    fi
}


stop(){
	/usr/bin/python26 /opt/membase/membase-backup/membase-backupd stop >/dev/null 2>&1
    if [ $? -eq 0 ];
    then
        echo "Stopped backup daemon successfully"
    else
        echo "Backup daemon is not running"
    fi
}

case "$1" in
    start)
        start 0
        ;;
    start-with-fullbackup)
        start 1
        ;;
    stop)
    stop
    ;;
    status)
    status; 
    ;;
    restart)
    stop; start 0;
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
esac


