#!/bin/bash
#Description: Wrapper method for zstore_cmd

#   Copyright 2013 Zynga Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

zstore_cmd=$(dirname $0)/zstore_cmd

if [ -z "$MAPPING_SERVER" ];
then
    echo MAPPING_SERVER not defined
    exit 1
fi

args=$(echo "$@" | sed "s|s3://|s3://$MAPPING_SERVER/|")

out="$($zstore_cmd $args)"
status=$?

if [ $status -ne 0 ];
then
    echo $out
    exit $status
fi

echo "$out" | sed "s|s3://[^/]*/|s3://|"

